version: '3'

services:
  webapitruservice:
    build: ..
    ports:
      - 6943:8080
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:6943/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - ENVIRONMENT = 
      - db=user id=dorian;database=doriandb;password=P@ssw0rd!;host=dorianpostgres
    networks:
      otel: 

  db:
    container_name: dorianpostgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dorian
      POSTGRES_DB: doriandb
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
     - ../TestsTRU/20240209.11.58.33.sql:/docker-entrypoint-initdb.d/a_init.sql
    networks:
        otel: 

  blackbox:
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.23.0
    restart: unless-stopped
    ports:
      - 9151:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../WebApiTRU/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      otel:

  prometheus:
    # https://github.com/prometheus/prometheus/releases
    image: prom/prometheus:v2.43.0
    hostname: prometheus
    restart: unless-stopped
    ports:
        - "9097:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../WebApiTRU/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
        - blackbox 
    networks:
      otel: 
  
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9141:9411
    networks:
      otel: 

  grafana:
    # https://github.com/grafana/grafana/releases
    image: grafana/grafana:9.4.7
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ../WebApiTRU/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    user: root
    ports:
      - "3090:3000"
    depends_on:
      - prometheus 
      - loki
    networks:
      otel: 
      
      
  loki:
    # https://github.com/grafana/loki/releases
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro      
      - ../WebApiTRU/loki/loki.yml:/etc/loki/local-config.yaml
      - loki:/data/loki
    restart: unless-stopped
    ports:
      - 30013:3100
    networks:
      otel:

  otel-collector:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/releases
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../WebApiTRU/otel/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped
    ports:
      - 10083:8888   # Prometheus metrics exposed by the collector
      - 8389:8889   # Prometheus exporter metrics
      - 4347:4317   # OTLP gRPC receiver
      - 9020:55679  # zpages
      - 43333:13133 # Health check
    networks:
      otel: 

  proxy:
    image: nginx
    depends_on:
      - webapitruservice
      - grafana
    container_name: dorian-proxy
    ports:
     - 5937:80
    volumes:
     - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      otel:

networks:
  otel:

volumes:
  prometheus:
  prometheus-data:
  grafana-data:
  loki:



       