scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response
    static_configs:
      - targets:
        - http://bensons_website:6001/healthcheck #Catalog API
        - http://bensons_website:6002/healthceck #Basket API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'etel-collector'
    scrape_interval: 10s
    static_configs:
    - targets: ['etel-collector:8889']
    - targets: ['etel-collector:8888']