name: Dorian's deployment to alex server
on:
  push:
    branches:
    - doriandocker
jobs:
  run-on-github-actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: "get rid of current composition"
        run: |
            pwd; ls -la
            cd ./ticketsrus-benson-dallin-dorian/Stagin
            docker compose down -v
            cd ../../
            rm -rf ./ticketsrus-benson-dallin-dorian
        working-directory: ./../../../../
      - name: "clone the github"
        run: |
            pwd; ls -la
            git clone --single-branch --branch doriandocker https://${{secrets.DORIAN_PAT}}@github.com/SnowSE/ticketsrus-benson-dallin-dorian.git
        working-directory: ./../../../../
      - name: "Turn on the docker containers"
        run: |
            pwd; ls -la
            cd ./ticketsrus-benson-dallin-dorian/Staging
            docker compose up --build -d
        working-directory: ./../../../../
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.DORIAN_TEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "correlationId": "0b72cc8a2cea509ba06b41892066784d7f602834",
              "themeColor": "#999",
              "title": "TheRealDeLorian push initialised workflow \"Dorian's deployment to alex server\"",
              "summary": "[SnowSE/ticketsrus-benson-dallin-dorian](https://github.com/SnowSE/ticketsrus-benson-dallin-dorian)",
              "sections": [
                {
                  "activityTitle": "No job context has been provided",
                  "activitySubtitle": "2024-02-20T17:32:33Z",
                  "activityImage": "https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/unknown.png"
                }
              ],
              "potentialAction": [
                {
                  "@type": "OpenUri",
                  "name": "Repository",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "https://github.com/SnowSE/ticketsrus-benson-dallin-dorian"
                    }
                  ]
                },
                {
                  "@type": "OpenUri",
                  "name": "Compare",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "https://github.com/SnowSE/ticketsrus-benson-dallin-dorian/compare/fff6296f7ed1...0b72cc8a2cea"
                    }
                  ]
                }
              ],
              "text": "**Changelog:**\n\n+ if this fails I did something right"
            }