name: dorian-deploy-to-server-1
on:
  push:
    branches: 
      - DorianCICD
jobs: 
  deploy:
    runs-on: [alex-office1]

    steps:
    - name: remove old code
      run: |
       docker compose down -v
       cd ../../
       rm -rf ./ticketsrus-benson-dallin-dorian
      working-directory: ./ticketsrus-benson-dallin-dorian/Staging 

    - name: Clone repo
      run: |
        git clone --single-branch --branch DorianCICD https://${{secrets.DORIAN_PAT}}@github.com/SnowSE/ticketsrus-benson-dallin-dorian.git

    - name: Start docker-compose
      run: |
        docker compose up --build -d
      working-directory: ./ticketsrus-benson-dallin-dorian/Staging 

