name: Dorian's deployment to alex server
on:
  push:
    branches:
    - doriandocker
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}"
  run-on-github-actions:
    runs-on: self-hosted
    steps:
      - name: "get rid of current composition"
        run: |
            pwd; ls -la
            cd ./ticketsrus-benson-dallin-dorian/Staging
            docker compose down -v
            cd ../../
            rm -rf ./ticketsrus-benson-dallin-dorian
        working-directory: ./../../../../
      - name: "clone the github"
        run: |
            pwd; ls -la
            git clone --single-branch --branch doriandocker https://${{secrets.DORIAN_PAT}}@github.com/SnowSE/ticketsrus-benson-dallin-dorian.git
        working-directory: ./../../../../
      - name: "Turn on the docker containers"
        run: |
            pwd; ls -la
            cd ./ticketsrus-benson-dallin-dorian/Staging
            docker compose up --build -d
        working-directory: ./../../../../
  if_failure:
    name: Only if failure
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.DORIAN_TEAMS_WEBHOOK }}
          raw: >-
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "title": "Dorian just got pwned!"
          }