name: dorian-deploy-to-server-1
on:
  push:
    branches:
      - DorianCICD
jobs:
  removeoldcode:
    runs-on: [alex-office4]
    steps:
      - name: remove old code
        run: |
          cd ./ticketsrus-benson-dallin-dorian/Staging
          docker compose down -v
          cd ../../
          rm -rf ./ticketsrus-benson-dallin-dorian
  clonerepository:
    runs-on: [alex-office4]
    needs: removeoldcode
    steps:
      - name: Clone repo
        run: |
          git clone --single-branch --branch DorianCICD https://${{secrets.DORIAN_PAT}}@github.com/SnowSE/ticketsrus-benson-dallin-dorian.git
  # Linting: 
  #   runs-on: [ alex-office4 ]
  #   needs: clonerepository
  #   steps: 
  #     - name: linting
  #       run: |
  #           cd ./ticketsrus-benson-dallin-dorian
  #           docker run -t --rm -v $(pwd):/appLint -w /appLint -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet format
  # BuildWarnings: 
  #   runs-on: [ alex-office4 ]
  #   # needs: Linting
  #   needs: clonerepository
  #   steps: 
  #     - name: buildwarnings
  #       run: |
  #           cd ./ticketsrus-benson-dallin-dorian
  #           docker run -t --rm -v $(pwd):/appBW -w /appBW -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet build -warnaserror
  deploy:
    runs-on: [alex-office4]
    needs: clonerepository
    steps:
      # - name: integrationtests
      #   run: |
      #     cd ./ticketsrus-benson-dallin-dorian/TestsTRU
      #     dotnet test
      - name: deploy docker
        run: |
          cd ./ticketsrus-benson-dallin-dorian/Staging
          docker compose up --build -d
          cd ../../
      - name: deploy k8s
        run: | 
          cd ./ticketsrus-benson-dallin-dorian
          docker build -t 144.17.92.12:5000/dorian/blazor-web:1 .
          docker push 144.17.92.12:5000/dorian/blazor-web:1
          
          cd ./kubeconfigs
            kubectl -n dorian delete configmap otel-config || true
            kubectl -n dorian create configmap otel-config --from-file=otel-collector-config.yml
            kubectl -n dorian delete configmap grafana-datasource-config || true
            kubectl -n dorian create configmap grafana-datasource-config --from-file=grafana-datasource.yml
          cd ..

          for file in ./kube; do
            echo "Applying $file"
            kubectl apply -f "$file"
          done
      - name: Microsoft Teams Failure Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.DORIAN_TEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "correlationId": "0b72cc8a2cea509ba06b41892066784d7f602834",
              "themeColor": "#999",
              "title": "Dorian's app just got pwned!",
              "summary": "[SnowSE/ticketsrus-benson-dallin-dorian](https://github.com/SnowSE/ticketsrus-benson-dallin-dorian)",
              "sections": [
                {
                  "activityTitle": "",
                  "activitySubtitle": "The deployment failed. Better luck next time.",
                  "activityImage": "https://cdn4.iconfinder.com/data/icons/web-design-and-development-88/64/web_application_error_crash_error-512.png"
                }
              ],
              "potentialAction": [
                {
                  "@type": "OpenUri",
                  "name": "Repository",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "https://github.com/SnowSE/ticketsrus-benson-dallin-dorian"
                    }
                  ]
                },
                {
                  "@type": "OpenUri",
                  "name": "Compare",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "https://github.com/SnowSE/ticketsrus-benson-dallin-dorian/compare/fff6296f7ed1...0b72cc8a2cea"
                    }
                  ]
                }
              ],
              "text": ""
            }
      - name: Microsoft Teams Success Notification
        uses: skitionek/notify-microsoft-teams@master
        if: success()
        with:
          webhook_url: ${{ secrets.DORIAN_TEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}


          